# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Ingredient.create(name: "lemon")
Ingredient.create(name: "ice")
Ingredient.create(name: "mint leaves")
Ingredient.create(name: "tomato juice")
Ingredient.create(name: "basil")
Ingredient.create(name: "Worcestershire sauce")
Ingredient.create(name: "Tabasco sauce")
Ingredient.create(name: "vodka")
Ingredient.create(name: "pepper")
Ingredient.create(name: "salt")
Ingredient.create(name: "celery salt")
Ingredient.create(name: "ginger beer")
Ingredient.create(name: "lime")
Ingredient.create(name: "sugar")
Ingredient.create(name: "cachaca")
Ingredient.create(name: "berries")
Ingredient.create(name: "light rum")
Ingredient.create(name: "strawberries")
Ingredient.create(name: "lemonade")
Ingredient.create(name: "club soda")
Ingredient.create(name: "triple sec")
Ingredient.create(name: "cranberry juice")
Ingredient.create(name: "lime juice")
Ingredient.create(name: "fresh lemon zest")
Ingredient.create(name: "tequila")
Ingredient.create(name: "orange juice")
Ingredient.create(name: "grenadine")
Ingredient.create(name: "cranberry juice")
